language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: demo/public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "yarn"
script:
  - "yarn run build --prefix-paths"
